### PR TITLE
Don't fetch snapshot again

### PR DESCRIPTION
**Pull request by benoist**
Fetching the snapshot on an error will lead to infinite loops
For example if a market doesn't exist it will return a 400 status code
Will keep looping forever

### CODE REVIEW

**Comment by bmancini55** [comment]
Good call on 400 errors. We still need retry logic for 429 (rate limit) or 500 errors.  

We can probably add a whitelist of allowed retries (429, 500).  

The other possible status codes (400, 4xx, 418) look like permanent failures of the request:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#general-api-information

**Comment by benoist** [comment]
In this case it's a request for a snapshot, I would argue it's better to let the user handle the failure instead of retrying. Cause the retries cannot be stopped and retrying a 429 error can result in longer IP bans

**Comment by bmancini55** [comment]
The biggest challenge with Binance is that subscribe/unsubscribe initiates disconnect and connect events. Snapshots get triggered on connection, so if we push retry to the user they will either need to:

* unsubscribe/subscribe (which exacerbates the problem)
* manually call the the reqeustLevel2Snapshot for the market

The retry code exists to makes subscribe a black box. The update stream starts and eventually a snapshot is taken. If we require the user to take some action on failures, the black box is broken and the subscription is now in an invalid state.<sup>1</sup>

I think a fix that doesn't break the black box but addresses concerns of IP ban is adding retry count + back off to prevent an infinite retry loop.  However, the question still remains, what happens when we reach the termination point.

I do think it makes sense to give the user control of how snapshots and retry are handled.  

A few architectural considerations:
1. CCXWS does not currently address subscription failures. I'll put an issue in for discussion on how this can be best cleaned up and addressed. Based on above, simply removing the subscription or triggering an unsubscribe can have undesirable consequences and that should be considered.

2. Binance, Binance Jersesy, bitFlyer, Bitstamp, and Kucoin all use REST Snapshot requests.  Any change we make to this client should be considered in the other clients as well.

3. Another ancillary issue is that the error event does not uniformly emit event data.  I'm going to create another issue for discussion about creating a uniform interface for error messages. For example, status code (how do we know that an error event is for a REST snapshot failure?), market (which market if any was this error emitted for), is there any data that this event pertains to?

**Comment by bmancini55** [comment]
Closing during cleanup. This is tracked via #103

**Pull request closed without merging**
