### PR TITLE
Added ping-pong support in gateio to mitigate often disconnects

### PR DESCRIPTION
**Pull request by rejdzu**
I've added support for ping-pong message between client-server. Current client is disconnected quite often when there is no communication on the channel.

### CODE REVIEW

**Comment by rejdzu** [comment]
Hi, I've modified code based on review. I've tested that clearinterval is called when I unplug my network cable. Since I took ping support from okex client, then this one also needs a fix. I can create separate PR for that but it uses already on connected event and probably callbacks have to be modified. Do you think that those _onConnectedInternal and _onDisconnectedInternal are ok names ? I would change okex accordingly

**Comment by bmancini55** [comment]
Thanks for the quick turnaround on the PR!  That would be awesome if you applied the same fixes to OKEx!  

On the changes:

I would probably name the methods `_startPing` and `_stopPing` so the name is semantic to the functionality.  But I'm fine either way.

You can also remove the falsy check on the call to `clearInterval` so it's just 

```
_stopPing() {
  clearInterval(this._pingInterval);
}
```

`clearInterval` does not throw if null, undefined, or an invalid timer handle is passed to it. This also makes it idempotent. So repeated calls to `clearInterval` with the same handle value will not throw either. So you should be ok just calling `clearInterval`.

**Comment by rejdzu** [comment]
It is ok for gateio, but okex already connects to connected event to run

_resetSemaphore() {
    this._sem = semaphore(5);
    this._hasSnapshot = new Set();
  }

then stopping and startping would not be quite ok in that client. Don't know what approach you want to take in general with that, because I is already couple of clients that have that and they all have different approaches

**Comment by bmancini55** [comment]
Events emitters allow multiple listeners on the same event. They will fire in order of subscription.   For OKEx, we can just add the same handlers as the Gateio client and it should work.   Ie:

```
constructor() {
    super("wss://real.okex.com:10441/websocket", "OKEx");

    this.on("connected", this._resetSemaphore.bind(this));
    this.on("connected", this._startPing.bind(this));
    this.on("disconnected", this._stopPing.bind(this));

    this.hasTickers = true;
    this.hasTrades = true;
    this.hasLevel2Snapshots = true;
    this.hasLevel2Updates = true;
  }
```

From a quick look it seems like Coinex may be the only other client that is using setInterval to send pings.  As a side thought, the codebase is due for some refactoring to consolidate this functionality though.

Sorry for asking you to jump through these hoops, it's just one of the things I'm looking for since Issue #60.

**Comment by rejdzu** [comment]
No worries, If it works and sits in the main repo then I don't have to go through hoops in the future. Besides that everyone will benefit from this change as it was causing issues in our project as well

**Comment by bmancini55** [comment]
Released in https://github.com/altangent/ccxws/releases/tag/v0.23.4

**Pull request merged**
