### PR TITLE
FTX client

### PR DESCRIPTION
**Pull request by hhagelbe**
Client for FTX exchange

Site: https://ftx.com/
Api: https://docs.ftx.com/#websocket-api

### CODE REVIEW

**Comment by bmancini55** [comment]
Awesome, thanks for the PR!  Will take a look at this today or tomorrow and let you know if any changes are required.

**Comment by hhagelbe** [comment]
> The implementation looks great! Couple things:
> 
> 1. The order book subscription code can be simplified by removing the `subscribeLevel2Snapshot` logic and setting `hasLevel2Snapshot` to false. Based on the docs, FTX first sends a snapshot, then sends updates, which would means it should only support "update" functionality. `hasLevel2Snapshots` should be false and the`subscribeLevel2Snapshot` logic can be removed.  That functionality is for when an exchange sends periodic snapshots, not just a snapshot+updates.
> 2. Is there a technical reason why you are limiting to spot markets only?
> 3. For order book snapshot and update objects, you should add the checksum value. That is a useful value for allowing people to validate their order book after time.
> 
> If you have any questions, let me know! Thanks

Hey, 
thanks for the review. 

1. I will check and fix this.
2. I limited to spot markets because there is no way currently to separate spot from futures. This would actually be nice feature so the market matching is not only based on 'base/quote' or 'exchange:base/quote'.
3. I will also check and add this.

I'll come back later with the fixes

**Comment by hhagelbe** [comment]
PR fixes added.

I removed the spot market limit. However i had to add a 'market' field in order to differentiate spot and futures from each other. Please tell me if there is a better way to do that.

**Comment by hhagelbe** [comment]
PR fixes added. 

I completely missed market as second argument. Hopefully fixes are now ok.

**Pull request merged**
