### PR TITLE
98 bitmex limited ticker w/cached data

### PR DESCRIPTION
**Pull request by evan-coygo**
for #98 

Combines quote and trades subscription data for limited ticker support w/last, ask, askVolume, bid, and bidVolume

I've tested this for a couple minutes using this demo script, let me know if you need anything else

```js
const BitMEXClient = require("../src/exchanges/bitmex-client");

client = new BitMEXClient();
const market = {
  id: 'XBTUSD',
  base: 'XBT',
  quote: 'USD'
};

client.subscribeTicker(market);
client.on('ticker', (ticker, thisMarket) => {
  console.log('got ticker event', JSON.stringify({
    market,
    ticker
  }, null, 2));
});
setTimeout(() => {
  console.log('=======timeout hit, unsubbing');
  client.unsubscribeTicker(market);
}, 5000);
```

### CODE REVIEW

**Comment by evan-coygo** [comment]
@bmancini55 anything else you need for this PR?

**Comment by bmancini55** [comment]
Sorry for the delay, plan to give it a good look shortly.

**Comment by evan-coygo** [comment]
@bmancini55 just a reminder in case you forgot about this one

**Comment by bmancini55** [comment]
@evan-coygo apologies this took so long to get into master, thanks for the contribution!  I did some refactoring to make the code more readable, but functionally it stayed the same.

**Pull request merged**
